### ISSUE TITLE
不知道POM报错是啥情况

### ISSUE THREAD

**Issue by hellocodesha** [wonderfulMorty/stuScoreManaSys#8]
Project build error: Non-resolvable parent POM for com.zy.liunao:StuScoreSys:0.0.1-SNAPSHOT: Failure to transfer org.springframework.boot:spring-boot-starter-parent:pom:2.0.4.RELEASE from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.0.4.RELEASE/spring-boot-starter-parent-2.0.4.RELEASE.pom and 'parent.relativePath' points at wrong local POM

**Comment by wonderfulMorty** [comment]
我用的是maven3版本吧，好像。并且，我配置了阿里的maven镜像的。
